version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_db
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
